name: oidc-poc

on:
  push:
    branches:
      - '*'

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Get ID token
        run: |
          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV

      - name: Exchange token with access and extract values
        env:
          ID_TOKEN: ${{ env.ID_TOKEN }}
          JFROG_PLATFORM_URL: https://elinaf.jfrog.io
        run: |
          response=$(curl -s -XPOST -H "Content-Type: application/json" "$JFROG_PLATFORM_URL/access/api/v1/oidc/token" \
            -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"test1322556\"}")
          
          ACCESS_TOKEN=$(echo $response | jq .access_token | tr -d '"')
          USERNAME=$(echo $response | jq .username | tr -d '"')

          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV

          echo "Access Token: ${ACCESS_TOKEN}"
          echo "Username: ${USERNAME}"

          docker login $JFROG_PLATFORM_URL -u "${USERNAME}" -p "${ACCESS_TOKEN}"
