name: "JFrog-GitHubb NPM Publish OIDC Integration"
on: push

# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'Jfrog-github'
      OIDC_PROVIDER: 'test1322'
      PLATFORM_REPO: 'npm'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v4
              
       - name: Print Specific Environment Variables
         run: |
           echo "OIDC_AUDIENCE is set to: ${{ env.OIDC_AUDIENCE }}"
           echo "OIDC_PROVIDER is set to: ${{ env.OIDC_PROVIDER }}"
           echo "JFrog URL is set to: ${{ secrets.JF_URL }}" # Caution: This will print the JFrog URL
       
       - name: Print All Environment Variables
         run: printenv

       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Test JFrog Connection
         run: |
            # Enable debug logging
            export DEBUG=1
            
            # Test connection
            jf rt ping || {
              echo "Ping failed. Checking configuration:"
              jf c show
              exit 1
            }
            
       - name: Test Repository Access
         if: success()
         run: |
            # List repositories to verify access
            jf rt repos --detailed
