name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push

permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_AUDIENCE: 'Jfrog-github'
      OIDC_PROVIDER: 'test1322'
      PLATFORM_REPO: 'npm'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v4
              
       - name: Print Specific Environment Variables
         run: |
           echo "OIDC_AUDIENCE is set to: ${{ env.OIDC_AUDIENCE }}"
           echo "OIDC_PROVIDER is set to: ${{ env.OIDC_PROVIDER }}"
           echo "JFrog URL is set to: ${{ secrets.JF_URL }}"

       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         id: setup-cli  # ID to reference outputs
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           oidc-audience: ${{ env.OIDC_AUDIENCE }}

       - name: Create pom.xml
         run: |
           cat <<EOF > pom.xml
           <?xml version="1.0" encoding="UTF-8"?>
           <project xmlns="http://maven.apache.org/POM/4.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
               <modelVersion>4.0.0</modelVersion>

               <groupId>org.apache.maven</groupId>
               <artifactId>maven-core</artifactId>
               <version>3.8.1</version>
               <packaging>jar</packaging>

               <repositories>
                   <repository>
                       <id>artifactory-releases</id>
                       <url>https://test.jfrog.io/artifactory/test-basselm-libs-release-local/</url>
                   </repository>
               </repositories>

               <distributionManagement>
                   <repository>
                       <id>artifactory-releases</id>
                       <url>https://test.jfrog.io/artifactory/test-basselm-libs-release-local/</url>
                   </repository>
               </distributionManagement>

               <build>
                   <plugins>
                       <plugin>
                           <groupId>org.apache.maven.plugins</groupId>
                           <artifactId>maven-deploy-plugin</artifactId>
                           <version>3.0.0-M1</version>
                           <executions>
                               <execution>
                                   <goals>
                                       <goal>deploy-file</goal>
                                   </goals>
                                   <configuration>
                                       <file>/path/to/maven-core-3.8.1.jar</file>
                                       <repositoryId>artifactory-releases</repositoryId>
                                       <url>https://test.jfrog.io/artifactory/test-basselm-libs-release-local/</url>
                                       <groupId>org.apache.maven</groupId>
                                       <artifactId>maven-core</artifactId>
                                       <version>3.8.1</version>
                                       <packaging>jar</packaging>
                                   </configuration>
                               </execution>
                           </executions>
                       </plugin>
                   </plugins>
               </build>
           </project>
           EOF

       - name: Verify pom.xml Exists
         run: ls -la && cat pom.xml

       - name: Create settings.xml
         run: |
           cat <<EOF > settings.xml
           <?xml version="1.0" encoding="UTF-8"?>
           <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.2.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
             <servers>
               <server>
                 <username>${{ steps.setup-cli.outputs.oidc-user }}</username>
                 <password>${{ steps.setup-cli.outputs.oidc-token }}</password>
                 <id>artifactory-releases</id>
               </server>
             </servers>
             <profiles>
               <profile>
                 <repositories>
                   <repository>
                     <id>artifactory-releases</id>
                     <url>https://test.jfrog.io/artifactory/test-basselm-libs-release-local/</url>
                   </repository>
                 </repositories>
                 <id>artifactory</id>
               </profile>
             </profiles>
             <activeProfiles>
               <activeProfile>artifactory</activeProfile>
             </activeProfiles>
           </settings>
           EOF

       - name: Run Maven Deploy
         run: mvn clean deploy -e -s settings.xml -f pom.xml
